### ISSUE TITLE
feature: zoom-in / zoom-out cursor

### ISSUE THREAD

**Issue by per-ludum** [noelboss/featherlight#113]
To get some more orientation on the click behavior, it would be nice adding the zoom-in and zoom-out cursor to featherlight. Of course, it's just a few lines of css:

```css
.zoom-in {
	cursor: -webkit-zoom-in;
	cursor: -moz-zoom-in;
	cursor: zoom-in;
}
.zoom-out {
	cursor: -webkit-zoom-out;
	cursor: -moz-zoom-out;
	cursor: zoom-out;
}
```

The more difficult part is the integration with the *closeOnClick* option ('background', 'anywhere', or false) the class allocation depends on. My javascript is not sufficient to make a pull req.

But maybe it would be an attractive little detail to add to featherlight.
