### ISSUE TITLE
Bootstrap 3.3.2 - unwanted scrollbars

### ISSUE THREAD

**Issue by K4T** [noelboss/featherlight#117]
Hello, featherlight have problem with the newest Twitter Bootstrap v3.3.2. You can see it here:
http://jsfiddle.net/k5Lwxf1L/1/

Notice additional scrollbars. Try changing viewport size and look what will happen.

**Solution:**
Overwrite CSS with those rules (just paste it into provided fiddle):
```css
@media all { 
 .featherlight .featherlight-content {
  padding: 0;
  border: none;
 }

 .featherlight .featherlight-image {
    max-width: 100%;  
    border: 20px solid #fff;
 }
}

@media only screen and (max-width: 1024px) {
 .featherlight .featherlight-content {
  padding: 0;
  border: none;
 }
}
```

Problem is probably caused by box-size reset in current version of Bootstrap. It is a bit different than in older Bootstrap. 

Your _onResize method, line: https://github.com/noelboss/featherlight/blob/master/src/featherlight.js#L489

Variable **w** have always wrong value, cause of wrong value returned by .css('width').

**Comment by gilcel** [comment]
Hmm, I thought it was more a problem of jQuery 1.8.0+ ? 
I've used bootstrap 3.3.2 along with jQuery 1.7.0 - 1.7.2 and no scrollbars.
However using jQuery 1.8.0 or 1.11.2, the vertical scroll-bars appears (Firefox 35+ and Safari 7+ tested)...
Anyone can confirm ?

**Comment by K4T** [comment]
I think it is not a jQuery problem, you can verify it by changing jQuery version on jsFiddle,
I also tested other browsers like IE11, Opera etc. All of them display scrollbars, My friend can confirm it too.

**Comment by danimalweb** [comment]
I had this problem too. Thanks for your css fix! Saved me some time :)

**Comment by gilcel** [comment]
Thank you K4T for your fix which works nicely, and it's effectively a bug which shows up with Bootstrap 3.3.x.
With your fix it works even with jquery 1.11.2 and bootstrap 3.3.4!

**Comment by hisamu** [comment]
+1 :+1: 

Solved my issue with big images, thanks :)

**Comment by arnisjuraga** [comment]
Nice, K4T - this fixes for big images, but still - if I use "gallery", because of navigation buttons, there are still vertical scroll for large images.

**Comment by noelboss** [comment]
Is this issue a sole issue of Bootstrap, or does it affect (i.e. large images) also standalone FL instances?

**Comment by noelboss** [comment]
The proposed solution dies only work with images... Test it on src/index.html with the other options...

**Comment by Galactopus** [comment]
This is not a Bootstrap problem. It's a jQuery problem with versions later than 1.7.2.
Just delete the Bootstrap files from your fiddle and try re-sizing vertically and you'll get a scrollbar.

K4T's css works to a point but it will start to distort the image at smaller sizes.

Unfortunately using jQuery migrate doesn't appear to help.

**Comment by cngodles** [comment]
Adding this to a non bootstap project fixed the scrollbars immediately.

**Comment by gabor-braun** [comment]
For me, a fix was
```css
.featherlight-inner {
  margin-top: 0px;
  margin-bottom: 0px;
}
```
to override the following rules of Bootstrap:
```css
img {
    margin-bottom: 24px;
    margin-top: 17px;
 }
```
Perhaps the stylesheet of FL should set all padding and margin values.
