### ISSUE TITLE
Remove border on images

### ISSUE THREAD

**Issue by garygreen** [noelboss/featherlight#203]
This isn't a biggie, but it would be nice if featherlight adapted a more 'minimal' approach toward styling the lightbox and ditched the old-style photograph white border. Also move the close button 'X' to not overlap the image, as sometimes it's difficult to see, depending on the image.

I realise these things are easy to change, but just thought it would be a nice thing to do straight out the box.

**Comment by kyletinsley** [comment]
I agree and have been trying to change the border styling without success.  Can someone let us know how to reduce/remove the border and move the close button to above the image?  Or at the very least, reduce/remove the border, keeping the overlapping close button.  Featherlight is awesome, btw!

**Comment by robneu** [comment]
FWIW, the [WordPress plugin](https://github.com/wpsitecare/wp-featherlight) I wrote adopts a slightly different style and doesn't include any borders. Feel free to use the [CSS](https://github.com/wpsitecare/wp-featherlight/blob/develop/css/wp-featherlight.css) or the [SCSS](https://github.com/wpsitecare/wp-featherlight/tree/develop/css/src) files if you like.

**Comment by AnnoyingTechnology** [comment]
```css

.featherlight.cleaner .featherlight-content {
    padding: 0;
    border-bottom:0;
}

.featherlight.cleaner .featherlight-previous {
    background: none;
    text-shadow: none;
}

.featherlight.cleaner .featherlight-next {
    background: none;
    text-shadow: none;
}
```

```js
$('.yourobjects').featherlightGallery({
	variant: 'cleaner
'});
```
