### ISSUE TITLE
[feature request] Prevent scrolling on html/body

### ISSUE THREAD

**Issue by corysimmons** [noelboss/featherlight#273]
When modals are expanded, it's nice if the html/body isn't able to scroll.

You can achieve this by applying `overflow: hidden` to both.

Need to be mindful that content can expand vertically further than screen so `overflow-y: auto` would need to be added to the lightbox container.

**Comment by marcandre** [comment]
What would be the impact on #77?

**Comment by corysimmons** [comment]
I don't think the `html, body {overflow: hidden}` styles would cascade to the `<iframe>` if it was on a different origin.

I'm too lazy to check if it'd affect it on same origin. If it did, maybe this would work:

```scss
html,
body {
  overflow: hidden; // disable for local viewport
}

html html {
  overflow: auto; // enable for child viewport
}
```
