### ISSUE TITLE
Unnecessary scrollbar on IFrames.

### ISSUE THREAD

**Issue by viswanathct** [noelboss/featherlight#305]
The following CSS rule makes scrollbars compulsory on IFrames. This makes embedded videos look odd.

The said rule:
```CSS
.featherlight-iframe .featherlight-content{
  border-bottom:0;
  padding:0;
  -webkit-overflow-scrolling:touch;
  overflow-y:scroll;
}
```

Is this really necessary?
